### ISSUE TITLE
Only xIV%?

### ISSUE THREAD

**Issue by TakRiuto** [encode32/PokeVisionFinder#16]
Is possible make this only catch pokemon based in IV?

**Comment by Hypertoken** [comment]
Not possible since the data returned from the skiplagged API doesn't contain IV values... This app doesn't use the Niantic API at all, thats where pokesniper comes in.

It would be possible, if PokeSniper2 would make the user.xml value <MinIVToCatch> work with manual sniping as well... however in its current state that only applies to autosniper, but I understand that it doesn't make sense from their perspective.

**Comment by sakiyako** [comment]
@TakRiuto No because it's currently not possible to find a pokemon's IV's until you capture the pokemon.

@Hypertoken "It would be possible, if PokeSniper2 would make the user.xml value work with manual sniping as well... however in its current state that only applies to autosniper, but I understand that it doesn't make sense from their perspective." 
That's not possible. And also the reason why their autosniper has that IV option is because the website they pull from is similar to a discord sniping chat that posts IV's with their coords. If you look at their website they use and the way it works then you would understand that the possibility of having an IV option with manual sniping is not achievable atm.
